---
title: Data Wrangling using Tidyverse
author: R package build
date: '2021-05-25'
slug: data-wrangling-using-tidyverse
categories:
  - Tidyverse
tags: []
---
## Imports the Hotels .csv file
```{r}
library(tidyverse)
hotels <- read_csv("hotels.csv")
head(hotels)
names(hotels)
```
## Select 
```{r}
select(hotels, lead_time)
select(hotels, hotel, lead_time)
## select(hotels, hotel, lead_time)
hotels %>%
  select(hotel, lead_time) %>%
  arrange(desc(lead_time))
```
## Select a range of variables
```{r}
hotels %>%
  select(hotel:arrival_date_month)
hotels %>%
  select(starts_with("arrival"))
```
## Select a range of rows/cases
```{r}
hotels %>%
  # We will select 1st, 5th, 8th, and 10th row
  slice(1:5)
hotels %>%
  filter(hotel == "City Hotel")
hotels %>%
  filter(
    adults == 0,
    children >= 1
  ) %>%
  select(adults, babies, children)
hotels %>%
  filter(
    adults == 0,
    children >= 1 & babies >= 1 # & means and
  ) %>%
  select(adults, babies, children) 
    
```
## Summarizing
```{r}
hotels %>%
  count(hotel, market_segment)
```
## Mutation
```{r}
little_ones <- hotels 
little_ones %<>%
  mutate(little_ones = children + babies) %>%
  select(children, babies, little_ones) %>%
  arrange(desc(little_ones))
```
## Summary
```{r}
summary <- hotels %>%
  group_by(hotel) %>%
  summarise(mean_adr = mean(adr))
  summary
  
```

