---
title: Data Import Assignment
author: R package build
date: '2021-06-01'
slug: data-import-assignment
categories:
  - Tidyverse
tags: []
---
## Import Nobel.csv file
```{r}
library(tidyverse)
nobel <- read_csv(file = "nobel.csv")
head(nobel)
```
## Write a CSV file
```{r}
df <- tribble(
  ~x, ~y,
  1,  "a",
  2,  "b",
  3,  "c"
)
write_csv(df, "df.csv")
```
## Dealing with bad names
```{r}
library(tidyverse)
edibnb_col_names <- read_csv("edibnb-badnames.csv",
                    col_names = c("id", "price", 
                    "neighbourhood", "accommodates",
                    "bathroom", "bedroom", 
                    "bed", "review_scores_rating", 
                     "n_reviews", "url"))
```
## Importing data with snake case variables
```{r}
edibnb_clean_names <- read_csv("edibnb-badnames.csv") %>%
  janitor::clean_names()
names(edibnb_clean_names)
```
## read df-na.csv
```{r}
read_csv("df-na.csv",  
         na = c("", "NA", ".", "9999", "Not applicable"))
```
## Reading an Xls file
```{r}
library(readxl)
fav_food <- read_excel("favourite-food.xlsx",
                       na = c("N/A", "99999")) %>%
  janitor::clean_names()
fav_food
fav_food <- fav_food %>%
  mutate(
    age = if_else(age == "five", "5", age),
    age = as.numeric(age)
    )
glimpse(fav_food)
```
## ETL of SES variable
```{r}
fav_food %>%
  count(ses)

fav_food <- fav_food %>%
  mutate(ses = fct_relevel(ses, "Low", "Middle", "High"))
fav_food %>%
  count(ses)
fav_food
```
## Putting it altogether
```{r}
fav_food <- read_excel("favourite-food.xlsx", na = c("N/A", "99999")) %>%
  janitor::clean_names() %>%
  mutate(
    age = if_else(age == "five", "5", age), 
    age = as.numeric(age),
    ses = fct_relevel(ses, "Low", "Middle", "High")
  )
fav_food
```