<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.83.1" />


<title>Fiting and Interpreting Models - Tarana-Fundamentals of Data Analystics</title>
<meta property="og:title" content="Fiting and Interpreting Models - Tarana-Fundamentals of Data Analystics">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/ToTheSky21">GitHub</a></li>
    
    <li><a href="https://twitter.com/IslamTajnin">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">5 min read</span>
    

    <h1 class="article-title">Fiting and Interpreting Models</h1>

    
    <span class="article-date">2021-06-15</span>
    

    <div class="article-content">
      
<script src="/2021/06/15/fiting-and-interpreting-models/index_files/header-attrs/header-attrs.js"></script>
<script src="/2021/06/15/fiting-and-interpreting-models/index_files/kePrint/kePrint.js"></script>
<link href="/2021/06/15/fiting-and-interpreting-models/index_files/lightable/lightable.css" rel="stylesheet" />


<div id="import-libraries" class="section level2">
<h2>Import Libraries</h2>
</div>
<div id="models-with-numerical-explanatory-variables" class="section level2">
<h2># Models with numerical explanatory variables</h2>
</div>
<div id="data-paris-paintings" class="section level2">
<h2>Data: Paris Paintings</h2>
<pre class="r"><code>pp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))</code></pre>
<ul>
<li>Number of observations: 3393</li>
<li>Number of variables: 61</li>
</ul>
</div>
<div id="goal-predict-height-from-width" class="section level2">
<h2>Goal: Predict height from width</h2>
<p><img src="/2021/06/15/fiting-and-interpreting-models/index_files/figure-html/height-width-plot-1.png" width="672" />
<img src="tidymodels.png" width="1440" />
## Step 1: Specify model</p>
<pre><code>## Linear Regression Model Specification (regression)</code></pre>
</div>
<div id="step-2-set-model-fittung-engine" class="section level2">
<h2>Step 2: Set model fittung “engine”</h2>
<pre recho="FALSE," warning="FALSE," message="FALSE"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) #linear model</code></pre>
</div>
<div id="step-3-fit-model-and-estimate-parameters" class="section level2">
<h2>Step 3: Fit model and estimate parameters</h2>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    3.62    0.254        14.3 8.82e-45
## 2 Width_in       0.781   0.00950      82.1 0</code></pre>
</div>
<div id="a-closer-look-at-model-output" class="section level2">
<h2>A closer look at model output</h2>
<p>.large[
<span class="math display">\[\widehat{height}_{i} = 3.6214 + 0.7808 \times width_{i}\]</span>]
—
.large[
<span class="math display">\[\widehat{height}_{i} = 3.62 + 0.781 \times width_{i}\]</span>]
—
## Slope and intercept
.large[
<span class="math display">\[\widehat{height}_{i} = 3.62 + 0.781 \times width_{i}\]</span>]
–
- <strong>Slope:</strong> For each additional inch the painting is wider, the height is expected to be higher, on average, by 0.781 inches.
–
- <strong>Intercept:</strong> Paintings that are 0 inches wide are expected to be 3.62 inches high, on average. (Does this make sense?)
—
## Correlation does not imply causation
Remember this when interpreting model coefficients
<img src="cell_phones.png" width="90%" />
.footnote[
Source: XKCD, <a href="https://xkcd.com/925/">Cell phones</a>]
—
## Visualizing residuals</p>
<p><img src="/2021/06/15/fiting-and-interpreting-models/index_files/figure-html/vis-res-1-1.png" width="70%" />
## Visualizing residuals (cont.)</p>
<p><img src="/2021/06/15/fiting-and-interpreting-models/index_files/figure-html/vis-res-2-1.png" width="70%" /></p>
<hr />
</div>
<div id="visualizing-residuals-cont." class="section level2">
<h2>Visualizing residuals (cont.)</h2>
<p><img src="/2021/06/15/fiting-and-interpreting-models/index_files/figure-html/vis-res-3-1.png" width="70%" />
# Models with categorical explanatory variables
—
## Categorical predictor with 2 levels
.pull-left-narrow[
.small[</p>
<pre><code>## # A tibble: 3,393 x 3
##    name      Height_in landsALL
##    &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;
##  1 L1764-2          37        0
##  2 L1764-3          18        0
##  3 L1764-4          13        1
##  4 L1764-5a         14        1
##  5 L1764-5b         14        1
##  6 L1764-6           7        0
##  7 L1764-7a          6        0
##  8 L1764-7b          6        0
##  9 L1764-8          15        0
## 10 L1764-9a          9        0
## 11 L1764-9b          9        0
## 12 L1764-10a        16        1
## 13 L1764-10b        16        1
## 14 L1764-10c        16        1
## 15 L1764-11         20        0
## 16 L1764-12a        14        1
## 17 L1764-12b        14        1
## 18 L1764-13a        15        1
## 19 L1764-13b        15        1
## 20 L1764-14         37        0
## # … with 3,373 more rows</code></pre>
<p>]
]
.pull-right-wide[
- <code>landsALL = 0</code>: No landscape features
- <code>landsALL = 1</code>: Some landscape features]
—
## Height &amp; landscape features</p>
<pre><code>## # A tibble: 2 x 5
##   term              estimate std.error statistic  p.value
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)          22.7      0.328      69.1 0       
## 2 factor(landsALL)1    -5.65     0.532     -10.6 7.97e-26</code></pre>
<table style="width:6%;">
<colgroup>
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th>## Height &amp; landscape features
<span class="math display">\[\widehat{Height_{in}} = 22.7 - 5.645~landsALL\]</span>
- <strong>Slope:</strong> Paintings with landscape features are expected, on average, to be 5.645 inches shorter than paintings that without landscape features
- Compares baseline level (<code>landsALL = 0</code>) to the other level (<code>landsALL = 1</code>)
- <strong>Intercept:</strong> Paintings that don’t have landscape features are expected, on average, to be 22.7 inches tall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>## Relationship between height and school</td>
</tr>
<tr class="even">
<td><code>## # A tibble: 7 x 5 ##   term            estimate std.error statistic p.value ##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; ## 1 (Intercept)        14.0       10.0     1.40  0.162 ## 2 school_pntgD/FL     2.33      10.0     0.232 0.816 ## 3 school_pntgF       10.2       10.0     1.02  0.309 ## 4 school_pntgG        1.65      11.9     0.139 0.889 ## 5 school_pntgI       10.3       10.0     1.02  0.306 ## 6 school_pntgS       30.4       11.4     2.68  0.00744 ## 7 school_pntgX        2.87      10.3     0.279 0.780</code></td>
</tr>
</tbody>
</table>
</div>
<div id="dummy-variables" class="section level2">
<h2>Dummy variables</h2>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
<ul>
<li>When the categorical explanatory variable has many levels, they’re encoded to <strong>dummy variables</strong></li>
<li><h2 id="each-coefficient-describes-the-expected-difference-between-heights-in-that-particular-school-compared-to-the-baseline-level">Each coefficient describes the expected difference between heights in that particular school compared to the baseline level</h2>
<h2 id="categorical-predictor-with-3-levels">Categorical predictor with 3+ levels</h2>
.pull-left-wide[
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
school_pntg
</th>
<th style="text-align:center;">
D_FL
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:center;">
G
</th>
<th style="text-align:center;">
I
</th>
<th style="text-align:center;">
S
</th>
<th style="text-align:center;">
X
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
D/FL
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
</tr>
</tbody>
</table>
]
.pull-right-narrow[
.small[</li>
</ul>
<pre><code>## # A tibble: 3,393 x 3
##    name      Height_in school_pntg
##    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;      
##  1 L1764-2          37 F          
##  2 L1764-3          18 I          
##  3 L1764-4          13 D/FL       
##  4 L1764-5a         14 F          
##  5 L1764-5b         14 F          
##  6 L1764-6           7 I          
##  7 L1764-7a          6 F          
##  8 L1764-7b          6 F          
##  9 L1764-8          15 I          
## 10 L1764-9a          9 D/FL       
## 11 L1764-9b          9 D/FL       
## 12 L1764-10a        16 X          
## 13 L1764-10b        16 X          
## 14 L1764-10c        16 X          
## 15 L1764-11         20 D/FL       
## 16 L1764-12a        14 D/FL       
## 17 L1764-12b        14 D/FL       
## 18 L1764-13a        15 D/FL       
## 19 L1764-13b        15 D/FL       
## 20 L1764-14         37 F          
## # … with 3,373 more rows</code></pre>
<p>]
]
—
## Relationship between height and school
.small[</p>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
<ul>
<li><strong>Austrian school (A)</strong> paintings are expected, on average, to be <strong>14 inches</strong> tall.</li>
<li><strong>Dutch/Flemish school (D/FL)</strong> paintings are expected, on average, to be <strong>2.33 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>French school (F)</strong> paintings are expected, on average, to be <strong>10.2 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>German school (G)</strong> paintings are expected, on average, to be <strong>1.65 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Italian school (I)</strong> paintings are expected, on average, to be <strong>10.3 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Spanish school (S)</strong> paintings are expected, on average, to be <strong>30.4 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li>Paintings whose school is <strong>unknown (X)</strong> are expected, on average, to be <strong>2.87 inches taller</strong> than <em>Austrian school</em> paintings.
]</li>
</ul>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

